-- MySQL Script generated by MySQL Workbench
-- Tue Oct 27 08:52:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esoftgraf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esoftgraf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esoftgraf` DEFAULT CHARACTER SET utf8mb4 ;
USE `esoftgraf` ;

-- -----------------------------------------------------
-- Table `esoftgraf`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP(1) NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  `deleted_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP(1) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(2555) NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  `deleted_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DOUBLE(11,2) NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  `deleted_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `esoftgraf`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`wishlist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wishlist_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_wishlist_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `esoftgraf`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`product_wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`product_wishlist` (
  `product_id` INT UNSIGNED NOT NULL,
  `wishlis_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `wishlis_id`),
  INDEX `fk_products_has_wishlist_wishlist1_idx` (`wishlis_id` ASC),
  INDEX `fk_products_has_wishlist_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_products_has_wishlist_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `esoftgraf`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_wishlist_wishlist1`
    FOREIGN KEY (`wishlis_id`)
    REFERENCES `esoftgraf`.`wishlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `color` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  `deleted_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`payment_methods` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  `deleted_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `payment_methods_id` INT UNSIGNED NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_payment_methods1_idx` (`payment_methods_id` ASC),
  INDEX `fk_orders_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_orders_payment_methods1`
    FOREIGN KEY (`payment_methods_id`)
    REFERENCES `esoftgraf`.`payment_methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `esoftgraf`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`product_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`product_order` (
  `product_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  INDEX `fk_products_has_orders_orders1_idx` (`order_id` ASC),
  INDEX `fk_products_has_orders_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_products_has_orders_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `esoftgraf`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_orders_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `esoftgraf`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`order_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`order_user` (
  `user_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `order_id`),
  INDEX `fk_users_has_orders_orders1_idx` (`order_id` ASC),
  INDEX `fk_users_has_orders_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `esoftgraf`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_orders_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `esoftgraf`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imageable_type` VARCHAR(45) NULL,
  `imageable_id` INT NULL,
  `path` VARCHAR(255) NULL,
  `category` VARCHAR(100) NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`config` (
  `key` INT NOT NULL,
  `value` TEXT(1) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esoftgraf`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esoftgraf`.`banners` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `created_at` TIMESTAMP(1) NULL,
  `updated_at` TIMESTAMP(1) NULL,
  `deleted_at` TIMESTAMP(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

START TRANSACTION;

USE `esoftgraf`;
INSERT INTO `esoftgraf`.`config` (`key`, `value`) VALUES (address, 'Rua Santana, 820 - centro');
INSERT INTO `esoftgraf`.`config` (`key`, `value`) VALUES (email, 'cursos@softgraf.com');
INSERT INTO `esoftgraf`.`config` (`key`, `value`) VALUES (phone, '(42) 3028-0449');

COMMIT;